name: CI/CD_PUSH

on:
    push:
        branches:
            - '**'
            - '!main'

jobs:
    validate-code:
        name: Build Project
        strategy:
            matrix:
                os: [ubuntu-latest]
                dotnet_version: [8.0.x]
            fail-fast: false
        runs-on: ${{ matrix.os }}

        steps:
            - name: Get the last commit
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: ${{ matrix.dotnet_version }}

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --no-restore

            - name: test
              run: dotnet test --no-restore --verbosity normal
